FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY gradlew .
COPY gradle gradle
RUN chmod +x gradlew

COPY build.gradle.kts .
COPY settings.gradle.kts .
RUN ./gradlew dependencies --no-daemon || true

COPY src src

CMD ["./gradlew", "test", "--tests", "mk.ukim.finki.studentsemesterenrollment.StudentSemesterEnrollmentE2ETests", "--no-daemon", "--stacktrace"]
